migration:
  enabled: true
  from: 37
  to: 36

# Keep all the microservices shutdown so that the previous version can be roll
# backed using helm rollback.
shutdown: true

# global value to define the PrivX images' repository
privxRepository: &privxRepo public.ecr.aws/sshprivx

# global value to define the PrivX images' version tag
privxVersion: &privxTag "37.0"

# ========== Privx settings restore ===============
jobs:
  restore:
    name: restore
    hook: post-upgrade
    weight: "-5"
    hookDeletePolicy: before-hook-creation
    image:
      repository: *privxRepo
      name: upgrader
      pullPolicy: IfNotPresent
      tag: *privxTag

    imagePullSecrets:
      - name: docker-pull-secret
    environment:
      - name: UPGRADER_CMD
        value: restore
      - name: PREVIOUS_VERSION
        value: 36.2.0
      - name: BACKUP_DIR
        value: <generated-backup-folder-placeholder>
    useGlobalPodSecurityContext: true
    securityContext: {}
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    volumes:
      enabled: true
      volumeMounts:
        - mountPath: /opt/privx/keyvault
          name: privx-config
          subPath: keyvault
        - mountPath: /opt/privx/etc
          name: privx-config
          subPath: privxetc
        - mountPath: /etc/nginx/ssl
          name: privx-config
          subPath: nginxssl
        - mountPath: /var/backups/privx/
          name: privx-config-backup
          subPath: privxbackup
        - mountPath: /etc/nginx/ca
          name: privx-ca-vol
      claims:
        - name: privx-config
          claimName: privx-claim
        - name: privx-config-backup
          claimName: privx-backup-claim
      secrets:
        - name: privx-ca-vol
          secretName: privx-ca-secret
    serviceAccount:
      create: false
      annotations: {}
      name: upgrader
    rbac:
      create: false
