migration:
  enabled: true
  from: 29
  to: 30

# Before anything else, PrivX is shutdown
shutdown: true

# global value to define the PrivX images' repository
privxRepository: &privxRepo public.ecr.aws/sshprivx

# global value to define the PrivX images' version tag
privxVersion: &privxTag "30.1"

# ========== Privx settings backup ===============
jobs:
  backup:
    name: backup
    hook: post-upgrade
    weight: "-5"
    hookDeletePolicy: before-hook-creation
    image:
      repository: *privxRepo
      name: upgrader
      pullPolicy: IfNotPresent
      tag: *privxTag

    imagePullSecrets:
      - name: docker-pull-secret
    environment:
      - name: UPGRADER_CMD
        value: backup
      - name: PRIVX_VERSION
        value: 29.0.0
    useGlobalPodSecurityContext: true
    securityContext: {}
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    volumes:
      enabled: true
      volumeMounts:
        - mountPath: /opt/privx/keyvault
          name: privx-config
          subPath: keyvault
        - mountPath: /opt/privx/etc
          name: privx-config
          subPath: privxetc
        - mountPath: /etc/nginx/ssl
          name: privx-config
          subPath: nginxssl
        - mountPath: /var/backups/privx/
          name: privx-config-backup
          subPath: privxbackup
        - mountPath: /etc/nginx/ca
          name: privx-ca-vol
      claims:
        - name: privx-config
          claimName: privx-claim
        - name: privx-config-backup
          claimName: privx-backup-claim
      configMaps:
        - name: privx-new-config
          configMap:
            name: new-config
        - name: privx-version-config
          configMap:
            name: version-config
      secrets:
        - name: privx-ca-vol
          secretName: privx-ca-secret
    serviceAccount:
      create: false
      annotations: {}
      name: upgrader
    rbac:
      create: false
