# migration-tool version config
# If configuration attribute is found in this list, override user old config with the new value.
# Otherwise, preserve old settings if possible.

################################# PrivX 2.2 #################################
[2.2.rdp-proxy.rdp-proxy]
# Turn on RDP smart card authentication
smartcard_authentication_enabled = true

[2.2.user-store.db]
data_version = "2"

[2.2.workflow-engine.db]
data_version = "2"

################################# PrivX 2.3 #################################

[2.3.user-store.db]
data_version = "3"

[2.3.shared-config.shared]
auth_address = "https://localhost/auth/api"

################################# PrivX 2.4 #################################

# Add global AD user filter to filter out disabled AD users by default
[2.4.role-store.ldap]
global_ad_user_filter = "(!userAccountControl:1.2.840.113556.1.4.803:=2)"

################################# PrivX 3.0 #################################

[3.0.shared-config.shared]
auth_address = "https://localhost/auth/api/v1"

################################# PrivX 4.0 #################################

[4.0.connection-manager.db]
data_version = "3"

[4.0.monitor-service.db]
data_version = "2"

################################# PrivX 5.0 #################################

[5.0.connection-manager.db]
data_version = "4"

[5.0.monitor-service.db]
data_version = "3"

[5.0.host-store.db]
data_version = "5"

[5.0.role-store.db]
data_version = "2"

################################# PrivX 6.0 #################################

[6.0.workflow-engine.db]
data_version = "3"

[6.0.monitor-service.db]
data_version = "4"

[6.0.keyvault.db]
data_version = "2"

################################# PrivX 7.0 #################################

[7.0.role-store.db]
data_version = "3"

[7.0.connection-manager.db]
data_version = "5"

################################# PrivX 8.0 #################################

[8.0.user-store.db]
data_version = "6"

[8.0.keyvault.db]
data_version = "3"

[8.0.monitor-service]
status_check_interval = 1

[8.0.role-store.db]
data_version = "4"

[8.0.host-store.db]
data_version = "6"

[8.0.oauth-shared-config]
client_ids = [
    "privx-ui",
    "privx-service",
    "privx-external",
]

################################# PrivX 9.0 #################################

[9.0.connection-manager.db]
data_version = "7"

[9.0.monitor-service.monitor-service]
status_check_interval = 10
housekeeping_interval = 8

[9.0.role-store.db]
data_version = "5"

[9.0.host-store]
listen_port = 8882

[9.0.monitor-service.db]
data_version = "6"

################################# PrivX 10.0 #################################

[10.0.host-store.db]
data_version = "7"


################################# PrivX 11.0 #################################

[11.0.host-store.db]
data_version = "8"

################################# PrivX 12.0 #################################

[12.0.user-store.db]
data_version = "7"

[12.0.host-store.db]
data_version = "9"

################################# PrivX 13.0 #################################

[13.0.role-store.db]
data_version = "6"

[13.0.host-store.db]
data_version = "10"

[13.0.monitor-service.db]
data_version = "7"

[13.0.workflow-engine.db]
data_version = "4"

################################# PrivX 14.0 #################################

[14.0.user-store.db]
data_version = "8"

[14.0.authorizer.db]
data_version = "2"

[14.0.role-store.db]
data_version = "7"

[14.0.host-store.db]
data_version = "11"

[14.0.connection-manager.db]
data_version = "8"

[14.0.monitor-service.db]
data_version = "8"

################################# PrivX 15.0 #################################

[15.0.workflow-engine.db]
data_version = "5"

[15.0.license-manager.db]
data_version = "2"

[15.0.role-store.db]
data_version = "8"

[15.0.user-store.db]
data_version = "9"

[15.0.monitor-service.db]
data_version = "9"

################################# PrivX 16.0 #################################

[16.0.host-store.db]
data_version = "12"

[16.0.connection-manager.db]
data_version = "9"

[16.0.role-store.db]
data_version = "9"

################################# PrivX 17.0 #################################
[17.0.host-store.db]
data_version = "14"

################################# PrivX 18.0 #################################
[18.0.workflow-engine.db]
data_version = "6"

[18.0.host-store.db]
data_version = "16"

[18.0.settings.db]
data_version = "2"

################################# PrivX 20.0 #################################
[20.0.authorizer.db]
data_version = "3"

################################# PrivX 21.0 #################################
[21.0.vault.db]
data_version = "2"

[21.0.settings.db]
data_version = "3"

[21.0.license-manager.db]
data_version = "3"

[21.0.monitor-service.db]
data_version = "10"

################################# PrivX 22.0 #################################
[22.0.workflow-engine.db]
data_version = "7"

[22.0.connection-manager.db]
data_version = "10"

[22.0.host-store.db]
data_version = "17"

################################# PrivX 23.0 #################################
[23.0.host-store.db]
data_version = "18"

[23.0.network-access-manager.db]
data_version = "2"

################################# PrivX 24.0 #################################
[24.0.role-store.db]
data_version = "10"

# These changes only apply to the Kubernetes deployment
[24.0.shared-config.shared]
send_audit_events_to_syslog = {{ if .Values.privx.syslog.enabled -}} true {{- else -}} false {{- end }}
send_audit_events_to_stdout = {{ if .Values.privx.syslog.enabled -}} false {{- else -}} true {{- end }}
syslog_address = "{{ .Values.ms.syslogservice.name }}:{{ .Values.ms.syslogservice.service.port }}"
audit_event_format = {{ if eq .Values.privx.syslog.audit.format "cef" -}} "cef" {{- else -}} "syslog" {{- end }}

################################# PrivX 25.0 #################################
[25.0.user-store.db]
data_version = "10"

################################# PrivX 26.0 #################################
[26.0.shared-config.shared]
local_user_store_address = "https://{{ .Values.ms.userstore.name }}:{{ .Values.ms.userstore.service.port }}/local-user-store/api/v1"
local_user_store_default = "https://{{ .Values.ms.userstore.name }}:{{ .Values.ms.userstore.service.port }}"

[26.0.vault.db]
data_version = "3"

[26.0.user-store.db]
data_version = "11"

[26.0.settings.db]
data_version = "4"

[26.0.connection-manager]
servicename = "connection-manager"
[26.0.connection-manager.tls]
certificate = "/opt/privx/cert/connection-manager.crt"
private_key = "/opt/privx/cert/connection-manager.key"

[26.0.host-store]
servicename = "host-store"
[26.0.host-store.tls]
certificate = "/opt/privx/cert/host-store.crt"
private_key = "/opt/privx/cert/host-store.key"

[26.0.license-manager]
servicename = "license-manager"
[26.0.license-manager.tls]
certificate = "/opt/privx/cert/license-manager.crt"
private_key = "/opt/privx/cert/license-manager.key"

[26.0.monitor-service]
servicename = "monitor-service"
[26.0.monitor-service.tls]
certificate = "/opt/privx/cert/monitor-service.crt"
private_key = "/opt/privx/cert/monitor-service.key"

[26.0.network-access-manager]
servicename = "network-access-manager"

[26.0.role-store]
servicename = "role-store"
[26.0.role-store.tls]
certificate = "/opt/privx/cert/role-store.crt"
private_key = "/opt/privx/cert/role-store.key"

[26.0.user-store]
servicename = "user-store"
[26.0.user-store.tls]
certificate = "/opt/privx/cert/user-store.crt"
private_key = "/opt/privx/cert/user-store.key"

[26.0.workflow-engine]
servicename = "workflow-engine"
[26.0.workflow-engine.tls]
certificate = "/opt/privx/cert/workflow-engine.crt"
private_key = "/opt/privx/cert/workflow-engine.key"

################################# PrivX 27.0 #################################
[27.0.role-store.db]
data_version = "11"

[27.0.auth-default-config.db]
data_version = "2"

################################# PrivX 28.0 #################################
[28.0.authorizer.db]
data_version = "4"

[28.0.role-store.db]
data_version = "12"

[28.0.secrets-manager.db]
data_version = "2"

[28.0.monitor-service.db]
data_version = "11"

[28.0.settings.db]
data_version = "5"

################################# PrivX 29.0 #################################
[29.0.user-store.db]
data_version = "12"

[29.0.network-access-manager.db]
data_version = "3"

[29.0.connection-manager.db]
data_version = "11"

[29.0.monitor-service.db]
data_version = "12"

################################# PrivX 30.0 #################################
[30.0.connection-manager.db]
data_version = "12"

[30.0.authorizer.db]
data_version = "5"

[30.0.role-store.db]
data_version = "13"

[30.0.host-store.db]
data_version = "19"

[30.0.oauth-shared-config]
client_ids = [
    "privx-ui",
    "privx-service",
    "privx-external",
    "privx-web-container",
]

[30.0.auth-default-config.db]
data_version = "3"

################################# PrivX 31.0 #################################
[31.0.authorizer.db]
data_version = "6"

[31.0.shared-config.db]
sslmode = '{{ .Values.db.sslmode | default "verify-full" }}'

################################# PrivX 32.0 #################################
[32.0.host-store.db]
data_version = "20"

[32.0.auth-default-config.db]
data_version = "4"

[32.0.keyvault.db]
data_version = "4"

################################# PrivX 33.0 #################################
[33.0.workflow-engine.db]
data_version = "8"

################################# PrivX 34.0 #################################
[34.0.workflow-engine.db]
data_version = "9"

[34.0.shared-config.notificationCache]
type = "db"
